// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdmhg5ombq00APvgkioqoU6ExGG4s8sww',
    appId: '1:100839405357:android:4c6f8ceb65fbd4643885a4',
    messagingSenderId: '100839405357',
    projectId: 'twentyone-b6a4a',
    databaseURL: 'https://twentyone-b6a4a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twentyone-b6a4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWgchQmD4Oyz7C8b3QOPBPut9W_pUk95s',
    appId: '1:100839405357:ios:981f762cbe2f757f3885a4',
    messagingSenderId: '100839405357',
    projectId: 'twentyone-b6a4a',
    databaseURL: 'https://twentyone-b6a4a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twentyone-b6a4a.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

}

