// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Configurazione del progetto Firebase per le diverse piattaforme,
/// generata automaticamente dalla FlutterFire CLI e usata da
/// `Firebase.initializeApp` in `main.dart`.
///
/// Non modificare a mano: per rigenerarla eseguire nuovamente il comando
/// `flutterfire configure`.
class DefaultFirebaseOptions {
  /// Restituisce le opzioni Firebase corrette in base alla piattaforma su
  /// cui l'app è in esecuzione (Android o iOS); lancia un'eccezione per
  /// web e per le piattaforme desktop non ancora configurate.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Opzioni Firebase per la build Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdmhg5ombq00APvgkioqoU6ExGG4s8sww',
    appId: '1:100839405357:android:4c6f8ceb65fbd4643885a4',
    messagingSenderId: '100839405357',
    projectId: 'twentyone-b6a4a',
    databaseURL: 'https://twentyone-b6a4a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twentyone-b6a4a.firebasestorage.app',
  );

  /// Opzioni Firebase per la build iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWgchQmD4Oyz7C8b3QOPBPut9W_pUk95s',
    appId: '1:100839405357:ios:981f762cbe2f757f3885a4',
    messagingSenderId: '100839405357',
    projectId: 'twentyone-b6a4a',
    databaseURL: 'https://twentyone-b6a4a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twentyone-b6a4a.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

}

