class Quote {
  final String text;
  final String author;
  final String category;

  const Quote({
    required this.text,
    required this.author,
    required this.category,
  });
}

const List<Quote> allQuotes = [
  Quote(text: 'La disciplina è il ponte tra gli obiettivi e i risultati.', author: 'Jim Rohn', category: 'Disciplina'),
  Quote(text: 'Prima formi le tue abitudini, poi le tue abitudini formano te.', author: 'John Dryden', category: 'Abitudini'),
  Quote(text: 'Ogni esperto era una volta un principiante. Ogni professionista era una volta un dilettante.', author: 'Robin Sharma', category: 'Mindset'),
  Quote(text: 'Il segreto del cambiamento è concentrare tutta la tua energia non nel combattere il vecchio, ma nel costruire il nuovo.', author: 'Socrate', category: 'Cambiamento'),
  Quote(text: 'Non è necessario essere grandi per iniziare, ma è necessario iniziare per essere grandi.', author: 'Zig Ziglar', category: 'Coraggio'),
  Quote(text: 'Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno.', author: 'Robert Collier', category: 'Disciplina'),
  Quote(text: 'Il modo in cui trascorri i tuoi giorni è il modo in cui trascorri la tua vita.', author: 'Annie Dillard', category: 'Abitudini'),
  Quote(text: 'Non aspettare. Il momento non sarà mai perfetto.', author: 'Napoleon Hill', category: 'Coraggio'),
  Quote(text: 'Sii il cambiamento che vuoi vedere nel mondo.', author: 'Mahatma Gandhi', category: 'Mindset'),
  Quote(text: 'Ogni giorno è una nuova opportunità per cambiare la tua vita.', author: 'Anonimo', category: 'Cambiamento'),
  Quote(text: 'Il corpo raggiunge ciò che la mente crede.', author: 'Jim Evans', category: 'Mindset'),
  Quote(text: 'Non puoi tornare indietro e cambiare l\'inizio, ma puoi cominciare dove sei e cambiare il finale.', author: 'C.S. Lewis', category: 'Cambiamento'),
  Quote(text: 'La gratitudine trasforma quello che abbiamo in abbastanza.', author: 'Anonimo', category: 'Gratitudine'),
  Quote(text: 'Inizia ogni giorno con un sorriso e mantienilo per tutto il giorno.', author: 'W.C. Fields', category: 'Gratitudine'),
  Quote(text: 'Il coraggio non è l\'assenza di paura, ma il giudizio che qualcos\'altro è più importante della paura.', author: 'Ambrose Redmoon', category: 'Coraggio'),
  Quote(text: 'Sii grato per quello che hai e avrai ancora di più.', author: 'Oprah Winfrey', category: 'Gratitudine'),
  Quote(text: 'Le piccole cose sono le grandi cose. Non possono essere separate.', author: 'Anonimo', category: 'Abitudini'),
  Quote(text: 'Un viaggio di mille miglia inizia con un singolo passo.', author: 'Lao Tzu', category: 'Coraggio'),
  Quote(text: 'Non cercare di essere migliore degli altri. Cerca di essere migliore di quello che eri ieri.', author: 'Anonimo', category: 'Mindset'),
  Quote(text: 'La vita non è misurata dal numero di respiri che facciamo, ma dai momenti che ci tolgono il respiro.', author: 'Maya Angelou', category: 'Gratitudine'),
  Quote(text: 'La motivazione ti fa partire. L\'abitudine ti fa andare avanti.', author: 'Jim Ryun', category: 'Abitudini'),
  Quote(text: 'Non importa quanto sei lento, purché tu non ti fermi.', author: 'Confucio', category: 'Disciplina'),
  Quote(text: 'Ogni mattina abbiamo due scelte: continuare a dormire e sognare, oppure svegliarci e inseguire i nostri sogni.', author: 'Anonimo', category: 'Coraggio'),
  Quote(text: 'Il cambiamento è difficile all\'inizio, complicato nel mezzo e bellissimo alla fine.', author: 'Robin Sharma', category: 'Cambiamento'),
  Quote(text: 'Non devi essere eccezionale per iniziare, ma devi iniziare per essere eccezionale.', author: 'Zig Ziglar', category: 'Coraggio'),
  Quote(text: 'Ciò che ottieni raggiungendo i tuoi obiettivi non è importante quanto ciò che diventi.', author: 'Henry David Thoreau', category: 'Mindset'),
  Quote(text: 'La vita premia coloro che agiscono, non coloro che aspettano il momento giusto.', author: 'Anonimo', category: 'Disciplina'),
  Quote(text: 'Sii abbastanza coraggioso da iniziare e abbastanza persistente da finire.', author: 'Anonimo', category: 'Coraggio'),
  Quote(text: 'Non è la forza del corpo che conta, ma la forza dello spirito.', author: 'J.R.R. Tolkien', category: 'Mindset'),
  Quote(text: 'Ogni giorno porta con sé la possibilità di un nuovo inizio.', author: 'Anonimo', category: 'Cambiamento'),
  Quote(text: 'La vera crescita inizia dove finisce la zona di comfort.', author: 'Anonimo', category: 'Coraggio'),
  Quote(text: 'Le abitudini sono le catene invisibili che ci guidano verso chi vogliamo diventare.', author: 'Anonimo', category: 'Abitudini'),
  Quote(text: 'Ringrazia ogni mattina per la nuova opportunità di amare, di essere amato e di fare la differenza.', author: 'Anonimo', category: 'Gratitudine'),
  Quote(text: 'Sii la persona che avresti voluto incontrare quando avevi bisogno di aiuto.', author: 'Anonimo', category: 'Mindset'),
  Quote(text: 'La vita è troppo breve per rimandare ciò che conta davvero.', author: 'Anonimo', category: 'Cambiamento'),
  Quote(text: 'Ogni piccolo passo verso la tua meta è una vittoria da celebrare.', author: 'Anonimo', category: 'Disciplina'),
  Quote(text: 'La gratitudine è la memoria del cuore.', author: 'Jean Baptiste Massieu', category: 'Gratitudine'),
  Quote(text: 'Non esistono scorciatoie per un posto che vale la pena raggiungere.', author: 'Beverly Sills', category: 'Disciplina'),
  Quote(text: 'Il meglio di sé non è una destinazione, è un percorso quotidiano.', author: 'Anonimo', category: 'Abitudini'),
  Quote(text: 'Agisci come se quello che fai facesse la differenza. Perché la fa.', author: 'William James', category: 'Mindset'),
  Quote(text: 'Ogni giorno fai qualcosa che il tuo futuro sé ringrazierà.', author: 'Anonimo', category: 'Abitudini'),
  Quote(text: 'Il successo non è la chiave della felicità. La felicità è la chiave del successo.', author: 'Albert Schweitzer', category: 'Mindset'),
  Quote(text: 'Non rimandare a domani quello che puoi fare oggi.', author: 'Benjamin Franklin', category: 'Disciplina'),
  Quote(text: 'Cadi sette volte, alzati otto.', author: 'Proverbio giapponese', category: 'Coraggio'),
  Quote(text: 'Il cambiamento inizia nel momento in cui decidi di non accettare più la tua situazione attuale.', author: 'Anonimo', category: 'Cambiamento'),
  Quote(text: 'La costanza è la virtù attraverso cui tutte le altre virtù danno i loro frutti.', author: 'Evelyn Waugh', category: 'Disciplina'),
  Quote(text: 'Sii abbastanza paziente da aspettare, abbastanza disciplinato da lavorare e abbastanza fiducioso da credere.', author: 'Anonimo', category: 'Disciplina'),
  Quote(text: 'Non è quello che hai, ma quello che fai con quello che hai a fare la differenza.', author: 'Woody Hayes', category: 'Mindset'),
  Quote(text: 'La vita è come andare in bicicletta. Per mantenere l\'equilibrio devi continuare a muoverti.', author: 'Albert Einstein', category: 'Abitudini'),
  Quote(text: 'Ogni momento è un nuovo inizio.', author: 'T.S. Eliot', category: 'Cambiamento'),
  Quote(text: 'Il tuo atteggiamento, non la tua apertura, determina la tua altitudine.', author: 'Zig Ziglar', category: 'Mindset'),
  Quote(text: 'Sii grato per i momenti difficili. Sono quelli che ti fanno crescere di più.', author: 'Anonimo', category: 'Gratitudine'),
  Quote(text: 'Non è la montagna che dobbiamo conquistare, ma noi stessi.', author: 'Edmund Hillary', category: 'Coraggio'),
  Quote(text: 'Ogni abitudine che costruisci oggi è un mattone del tuo futuro.', author: 'Anonimo', category: 'Abitudini'),
  Quote(text: 'La forza non viene dal vincere. Le tue lotte sviluppano la tua forza.', author: 'Arnold Schwarzenegger', category: 'Coraggio'),
  Quote(text: 'Smetti di desiderare e inizia a fare.', author: 'Walt Disney', category: 'Disciplina'),
  Quote(text: 'Sii la luce che vorresti vedere nel mondo.', author: 'Anonimo', category: 'Mindset'),
  Quote(text: 'Il passato non può essere cambiato. Il futuro è ancora nelle tue mani.', author: 'Anonimo', category: 'Cambiamento'),
  Quote(text: 'Ringrazia per quello che hai. Impegnarti per quello che vuoi.', author: 'Anonimo', category: 'Gratitudine'),
  Quote(text: 'La vita è troppo importante per essere presa sul serio.', author: 'Oscar Wilde', category: 'Mindset'),
  Quote(text: 'Non c\'è niente di nobile nell\'essere superiore a qualcun altro. La vera nobiltà è essere superiori a chi eri ieri.', author: 'Ernest Hemingway', category: 'Mindset'),
  Quote(text: 'Il momento presente è l\'unico momento disponibile per noi, ed è la porta verso tutti i momenti.', author: 'Thich Nhat Hanh', category: 'Abitudini'),
  Quote(text: 'Non aver paura di crescere lentamente. Temi solo di restare fermo.', author: 'Proverbio cinese', category: 'Coraggio'),
  Quote(text: 'La gratitudine non è solo le parole che diciamo, ma la vita che viviamo.', author: 'Anonimo', category: 'Gratitudine'),
  Quote(text: 'Fai di ogni giorno un capolavoro.', author: 'John Wooden', category: 'Disciplina'),
  Quote(text: 'Il coraggio è resistenza alla paura, padronanza della paura, non assenza di paura.', author: 'Mark Twain', category: 'Coraggio'),
  Quote(text: 'Non aspettare le condizioni perfette per iniziare. Inizia e le condizioni diventeranno perfette.', author: 'Alan Cohen', category: 'Coraggio'),
  Quote(text: 'Le abitudini sono prima ragnatele, poi funi.', author: 'Proverbio spagnolo', category: 'Abitudini'),
  Quote(text: 'Il cambiamento è l\'unica costante nella vita.', author: 'Eraclito', category: 'Cambiamento'),
  Quote(text: 'Apprezza quello che hai prima che diventi quello che avevi.', author: 'Anonimo', category: 'Gratitudine'),
  Quote(text: 'La disciplina è fare ciò che devi fare anche quando non ne hai voglia.', author: 'Anonimo', category: 'Disciplina'),
  Quote(text: 'Il successo è camminare da un fallimento all\'altro senza perdere l\'entusiasmo.', author: 'Winston Churchill', category: 'Coraggio'),
  Quote(text: 'Ogni giorno ti svegli è già un motivo per essere grati.', author: 'Anonimo', category: 'Gratitudine'),
  Quote(text: 'Non è mai troppo tardi per essere quello che avresti potuto essere.', author: 'George Eliot', category: 'Cambiamento'),
  Quote(text: 'Pensa in grande, agisci in piccolo, inizia ora.', author: 'Anonimo', category: 'Disciplina'),
  Quote(text: 'La mente è tutto. Diventi ciò che pensi.', author: 'Buddha', category: 'Mindset'),
  Quote(text: 'Chi vuole fare trova un modo. Chi non vuole fare trova una scusa.', author: 'Anonimo', category: 'Disciplina'),
  Quote(text: 'Non smettere mai di imparare, perché la vita non smette mai di insegnare.', author: 'Anonimo', category: 'Mindset'),
  Quote(text: 'Il futuro appartiene a coloro che credono nella bellezza dei propri sogni.', author: 'Eleanor Roosevelt', category: 'Coraggio'),
  Quote(text: 'Costruisci buone abitudini e lascia che siano loro a guidarti.', author: 'Anonimo', category: 'Abitudini'),
  Quote(text: 'La semplicità è la sofisticazione suprema.', author: 'Leonardo da Vinci', category: 'Mindset'),
  Quote(text: 'Non puoi controllare tutto nella vita, ma puoi controllare come reagisci.', author: 'Anonimo', category: 'Mindset'),
  Quote(text: 'Sii coraggioso abbastanza da vivere la vita che vuoi davvero vivere.', author: 'Anonimo', category: 'Coraggio'),
  Quote(text: 'Il cambiamento più difficile da fare è quello interiore. Ed è anche il più importante.', author: 'Anonimo', category: 'Cambiamento'),
  Quote(text: 'Ogni mattina è una seconda possibilità.', author: 'Anonimo', category: 'Gratitudine'),
  Quote(text: 'La perseveranza non è una lunga corsa. È tante piccole corse una dopo l\'altra.', author: 'Walter Elliot', category: 'Disciplina'),
  Quote(text: 'Trasforma le tue ferite in saggezza.', author: 'Oprah Winfrey', category: 'Cambiamento'),
  Quote(text: 'Non guardare indietro. Non sei diretto da quella parte.', author: 'Anonimo', category: 'Cambiamento'),
  Quote(text: 'La crescita personale inizia al confine della tua zona di comfort.', author: 'Anonimo', category: 'Coraggio'),
  Quote(text: 'Sii la persona che avresti bisogno di essere per ottenere la vita che vuoi avere.', author: 'Anonimo', category: 'Mindset'),
  Quote(text: 'L\'unico modo per fare un grande lavoro è amare quello che fai.', author: 'Steve Jobs', category: 'Mindset'),
  Quote(text: 'Ogni giorno è un dono. Ecco perché si chiama presente.', author: 'Anonimo', category: 'Gratitudine'),
  Quote(text: 'Le grandi imprese non si compiono con la forza, ma con la perseveranza.', author: 'Samuel Johnson', category: 'Disciplina'),
  Quote(text: 'Il tuo solo competitor è chi eri ieri.', author: 'Anonimo', category: 'Mindset'),
  Quote(text: 'Inizia dove sei. Usa quello che hai. Fai quello che puoi.', author: 'Arthur Ashe', category: 'Coraggio'),
  Quote(text: 'La gratitudine apre la pienezza della vita.', author: 'Melodie Beattie', category: 'Gratitudine'),
  Quote(text: 'Non è importante quante volte cadi, ma quante volte ti rialzi.', author: 'Vince Lombardi', category: 'Coraggio'),
  Quote(text: 'Un\'abitudine non si può eliminare, solo sostituire.', author: 'Charles Duhigg', category: 'Abitudini'),
  Quote(text: 'Il modo migliore per prevedere il futuro è crearlo.', author: 'Peter Drucker', category: 'Cambiamento'),
  Quote(text: 'Vivi come se dovessi morire domani. Impara come se dovessi vivere per sempre.', author: 'Mahatma Gandhi', category: 'Abitudini'),
];

Quote getQuoteOfDay() {
  final dayOfYear = DateTime.now().difference(DateTime(DateTime.now().year, 1, 1)).inDays;
  return allQuotes[dayOfYear % allQuotes.length];
}
